create table MOCK_DATA (
	id INT,
	product VARCHAR(50)
);
insert into MOCK_DATA (id, product) values (1, 'Lettuce - Red Leaf');
insert into MOCK_DATA (id, product) values (2, 'Beans - Fava Fresh');
insert into MOCK_DATA (id, product) values (3, 'Steampan - Lid For Half Size');
insert into MOCK_DATA (id, product) values (4, 'Juice - Orangina');
insert into MOCK_DATA (id, product) values (5, 'Pepsi - 600ml');
insert into MOCK_DATA (id, product) values (6, 'Ice - Clear, 300 Lb For Carving');
insert into MOCK_DATA (id, product) values (7, 'Beef Striploin Aaa');
insert into MOCK_DATA (id, product) values (8, 'Beer - Rickards Red');
insert into MOCK_DATA (id, product) values (9, 'Juice - Ocean Spray Cranberry');
insert into MOCK_DATA (id, product) values (10, 'Beef - Bones, Cut - Up');
insert into MOCK_DATA (id, product) values (11, 'Wine - White, Cooking');
insert into MOCK_DATA (id, product) values (12, 'Beef - Ox Tail, Frozen');
insert into MOCK_DATA (id, product) values (13, 'Sour Puss Raspberry');
insert into MOCK_DATA (id, product) values (14, 'Muffin - Mix - Strawberry Rhubarb');
insert into MOCK_DATA (id, product) values (15, 'Sherbet - Raspberry');
insert into MOCK_DATA (id, product) values (16, 'Coffee - Flavoured');
insert into MOCK_DATA (id, product) values (17, 'Yogurt - Assorted Pack');
insert into MOCK_DATA (id, product) values (18, 'Iced Tea Concentrate');
insert into MOCK_DATA (id, product) values (19, 'Veal - Slab Bacon');
insert into MOCK_DATA (id, product) values (20, 'Yogurt - French Vanilla');
insert into MOCK_DATA (id, product) values (21, 'Plasticforkblack');
insert into MOCK_DATA (id, product) values (22, 'Pumpkin');
insert into MOCK_DATA (id, product) values (23, 'Mustard - Individual Pkg');
insert into MOCK_DATA (id, product) values (24, 'Bagelers');
insert into MOCK_DATA (id, product) values (25, 'Truffle Shells - Semi - Sweet');
insert into MOCK_DATA (id, product) values (26, 'Shichimi Togarashi Peppeers');
insert into MOCK_DATA (id, product) values (27, 'Juice - Grape, White');
insert into MOCK_DATA (id, product) values (28, 'Whmis - Spray Bottle Trigger');
insert into MOCK_DATA (id, product) values (29, 'Sherbet - Raspberry');
insert into MOCK_DATA (id, product) values (30, 'Brandy Cherry - Mcguinness');
insert into MOCK_DATA (id, product) values (31, 'Rice - 7 Grain Blend');
insert into MOCK_DATA (id, product) values (32, 'Sterno - Chafing Dish Fuel');
insert into MOCK_DATA (id, product) values (33, 'Cake - Lemon Chiffon');
insert into MOCK_DATA (id, product) values (34, 'Turkey - Whole, Fresh');
insert into MOCK_DATA (id, product) values (35, 'Lamb - Leg, Bone In');
insert into MOCK_DATA (id, product) values (36, 'Soap - Mr.clean Floor Soap');
insert into MOCK_DATA (id, product) values (37, 'Tea - Decaf 1 Cup');
insert into MOCK_DATA (id, product) values (38, 'Lemonade - Mandarin, 591 Ml');
insert into MOCK_DATA (id, product) values (39, 'Bread Crumbs - Japanese Style');
insert into MOCK_DATA (id, product) values (40, 'Pork - Bacon, Double Smoked');
insert into MOCK_DATA (id, product) values (41, 'Coffee - French Vanilla Frothy');
insert into MOCK_DATA (id, product) values (42, 'Sugar - Cubes');
insert into MOCK_DATA (id, product) values (43, 'Tea - Darjeeling, Azzura');
insert into MOCK_DATA (id, product) values (44, 'Creamers - 10%');
insert into MOCK_DATA (id, product) values (45, 'Chicken - Wings, Tip Off');
insert into MOCK_DATA (id, product) values (46, 'Coffee - Flavoured');
insert into MOCK_DATA (id, product) values (47, 'Cheese - St. Andre');
insert into MOCK_DATA (id, product) values (48, 'Cake Slab');
insert into MOCK_DATA (id, product) values (49, 'Yokaline');
insert into MOCK_DATA (id, product) values (50, 'Food Colouring - Pink');
insert into MOCK_DATA (id, product) values (51, 'Cheese - Gouda');
insert into MOCK_DATA (id, product) values (52, 'Muffin Mix - Morning Glory');
insert into MOCK_DATA (id, product) values (53, 'Tomatoes - Roma');
insert into MOCK_DATA (id, product) values (54, 'Wine - Maipo Valle Cabernet');
insert into MOCK_DATA (id, product) values (55, 'Cream - 18%');
insert into MOCK_DATA (id, product) values (56, 'Sauce - Rosee');
insert into MOCK_DATA (id, product) values (57, 'Chicken - Leg, Fresh');
insert into MOCK_DATA (id, product) values (58, 'Beer - Maudite');
insert into MOCK_DATA (id, product) values (59, 'Sugar - Crumb');
insert into MOCK_DATA (id, product) values (60, 'Macaroons - Homestyle Two Bit');
insert into MOCK_DATA (id, product) values (61, 'Capers - Pickled');
insert into MOCK_DATA (id, product) values (62, 'Pike - Frozen Fillet');
insert into MOCK_DATA (id, product) values (63, 'Bread - Frozen Basket Variety');
insert into MOCK_DATA (id, product) values (64, 'Lamb - Shoulder, Boneless');
insert into MOCK_DATA (id, product) values (65, 'Pastry - Banana Tea Loaf');
insert into MOCK_DATA (id, product) values (66, 'Chinese Foods - Thick Noodles');
insert into MOCK_DATA (id, product) values (67, 'Lemon Tarts');
insert into MOCK_DATA (id, product) values (68, 'Bread - Petit Baguette');
insert into MOCK_DATA (id, product) values (69, 'Toamtoes 6x7 Select');
insert into MOCK_DATA (id, product) values (70, 'Veal - Brisket, Provimi, Bone - In');
insert into MOCK_DATA (id, product) values (71, 'Table Cloth - 53x69 Colour');
insert into MOCK_DATA (id, product) values (72, 'Squid - Breaded');
insert into MOCK_DATA (id, product) values (73, 'Swiss Chard - Red');
insert into MOCK_DATA (id, product) values (74, 'Tomatoes - Orange');
insert into MOCK_DATA (id, product) values (75, 'Tea - Vanilla Chai');
insert into MOCK_DATA (id, product) values (76, 'Gingerale - Schweppes, 355 Ml');
insert into MOCK_DATA (id, product) values (77, 'Lentils - Green Le Puy');
insert into MOCK_DATA (id, product) values (78, 'Shrimp - 16 - 20 Cooked, Peeled');
insert into MOCK_DATA (id, product) values (79, 'Veal - Tenderloin, Untrimmed');
insert into MOCK_DATA (id, product) values (80, 'Lentils - Green, Dry');
insert into MOCK_DATA (id, product) values (81, 'Yoplait Drink');
insert into MOCK_DATA (id, product) values (82, 'Cranberries - Frozen');
insert into MOCK_DATA (id, product) values (83, 'Tart Shells - Sweet, 4');
insert into MOCK_DATA (id, product) values (84, 'Beef - Chuck, Boneless');
insert into MOCK_DATA (id, product) values (85, 'Veal - Kidney');
insert into MOCK_DATA (id, product) values (86, 'Icecream - Dstk Strw Chseck');
insert into MOCK_DATA (id, product) values (87, 'Cheese - Mix');
insert into MOCK_DATA (id, product) values (88, 'Compound - Raspberry');
insert into MOCK_DATA (id, product) values (89, 'Wine - White Cab Sauv.on');
insert into MOCK_DATA (id, product) values (90, 'Apron');
insert into MOCK_DATA (id, product) values (91, 'Bread - Raisin Walnut Pull');
insert into MOCK_DATA (id, product) values (92, 'Lime Cordial - Roses');
insert into MOCK_DATA (id, product) values (93, 'Country Roll');
insert into MOCK_DATA (id, product) values (94, 'Nantucket - Carrot Orange');
insert into MOCK_DATA (id, product) values (95, 'Mushroom - Morels, Dry');
insert into MOCK_DATA (id, product) values (96, 'Steampan - Lid For Half Size');
insert into MOCK_DATA (id, product) values (97, 'Snapple - Mango Maddness');
insert into MOCK_DATA (id, product) values (98, 'Bread - Hamburger Buns');
insert into MOCK_DATA (id, product) values (99, 'Banana - Leaves');
insert into MOCK_DATA (id, product) values (100, 'Oranges - Navel, 72');
